name: ci
# https://github.com/actions/starter-workflows/blob/master/ci/npm-publish.yml
on:
  [push,pull_request]
# https://github.com/actions/starter-workflows/issues/158
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: ci
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn && yarn run ci
      - run: yarn run test

      - name: check process start
        working-directory: ./examples/websocket-chat/game-server
        run: node ci-test.js
        

