name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0
    - run: git checkout origin/master -B master
    - run: git config --global user.email "mybios@qq.com"
    - run: git config --global user.name "mybios"
    - run: git config --global credential.helper store
    - run: git remote set-url origin https://${GITHUB_TOKEN}@github.com/node-pinus/pinus.git
    - run: npm set unsafe-perm true -g
    - run: npm set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN -g
    - run: npm set username "mybios" -g
    - run: npm set email "mybios@qq.com" -g
    - run: echo "git user:"
    - run: git config user.name
    - run: echo "npm user:"
    - run: npm whoami
    - run: git status
    - run: yarn install
    - run: yarn build
    - run: yarn run publish --cd-version patch --yes
    env: # More info about the environment variables in the README
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
